if [[ ${EUID} == 0 ]] ; then
    PS1='\[\033[01;31m\]\h\[\033[01;34m\] \W \$\[\033[00m\] '
else
    PS1='\[\033[01;32m\]\u@\h\[\033[01;34m\] \w \$\[\033[00m\] '
fi


export PATH="$PATH:$HOME/bin"
export PATH="$PATH:$HOME/.local/bin"
export GOPATH=$HOME/go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
# export VISUAL="vim"
export EDITOR="vim"

alias ls='ls --color=auto'
alias make='make -j8'

HISTSIZE=4096

