PROMPT='%F{green}%n%f@%F{magenta}%m%f %F{blue}%B%~%b%f %# '
RPROMPT='[%F{yellow}%?%f]'

autoload -Uz compinit promptinit
compinit
promptinit

export PATH="$PATH:$HOME/bin"
export PATH="$PATH:$HOME/.local/bin"
export GOPATH=$HOME/go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
# export VISUAL="vim"
export EDITOR="vim"

alias ls='ls --color=auto'
alias make='make -j8'

HISTSIZE=4096

